version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:3000"
    environment:
      - WB_PORT=${WB_PORT}
      - DB_STRING=${DB_STRING}
    depends_on:
      - mongo
    env_file:
      - .env 

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: