name: Publicar Imagen de Docker en Docker Hub

# Este flujo de trabajo se ejecuta cada vez que hay un push a la rama 'main'
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    # Usamos la última versión de Ubuntu para ejecutar nuestro trabajo
    runs-on: ubuntu-latest

    steps:
      # 1. Obtenemos el código del repositorio
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Iniciamos sesión en Docker Hub
      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Construimos la imagen y la publicamos
      - name: Construir y publicar la imagen de Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-server-app:latest